### ISSUE TITLE
zeroize's cargo test fails immediately

### ISSUE THREAD

**Issue by burdges** [iqlusioninc/crates#237] opened 2019-07-25 10:49 UTC
There is seemingly some bug in the proc macros
```
error: proc-macro derive panicked
 --> zeroize/tests/zeroize_derive.rs:7:14
  |
7 |     #[derive(Zeroize)]
  |              ^^^^^^^
  |
  = help: message: unknown zeroize attribute: (drop)
```

I must work around this anyways though until dalek adopts zeroize

**Comment by tarcieri** [comment] 2019-07-25 13:58
These proc macros are used in several projects, although the attribute parser could definitely use some work.

Can you provide a failing code example?

**Comment by burdges** [comment] 2019-07-25 14:09
`cargo test` suffices.  It's maybe a miss-matched version for the zeroize_derive crate?

**Comment by tarcieri** [comment] 2019-07-25 14:14
I cannot reproduce your issue. The tests also run in CI every time any change is made to this repo:

```
$ cargo test
    Finished dev [unoptimized + debuginfo] target(s) in 0.15s
     Running /Users/bascule/src/iqlusion/crates/target/debug/deps/zeroize-868d63cfefbad716

running 5 tests
test tests::zeroize_box ... ok
test tests::zeroize_vec ... ok
test tests::zeroize_vec_past_len ... ok
test tests::zeroize_byte_arrays ... ok
test tests::zeroize_string ... ok

test result: ok. 5 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running /Users/bascule/src/iqlusion/crates/target/debug/deps/zeroize_derive-2cd2a713b1ce329b

running 2 tests
test custom_derive_tests::derive_tuple_struct_test ... ok
test custom_derive_tests::derive_struct_test ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests zeroize

running 4 tests
test src/lib.rs -  (line 69) ... ok
test src/lib.rs -  (line 95) ... ok
test src/lib.rs -  (line 80) ... ok
test src/lib.rs -  (line 24) ... ok

test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by burdges** [comment] 2019-07-25 14:33
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=bac38f5fb1ac22f94f5094cc2ca47651

**Comment by tarcieri** [comment] 2019-07-25 14:35
The `zeroize` crate is not available in the playground:

```
error[E0432]: unresolved import `zeroize`
```

**Comment by burdges** [comment] 2019-07-25 14:38
I see the same error I copied above.  Anyways I'll show the bash version:
```
$ git clone https://github.com/iqlusioninc/crates
Cloning into 'crates'...
remote: Enumerating objects: 36, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 3037 (delta 13), reused 17 (delta 6), pack-reused 3001
Receiving objects: 100% (3037/3037), 842.65 KiB | 1.66 MiB/s, done.
Resolving deltas: 100% (1670/1670), done.
$ cd crates/zeroize
$ cargo test
   Compiling proc-macro2 v0.4.30
   Compiling unicode-xid v0.1.0
   Compiling syn v0.15.39
   Compiling quote v0.6.13
   Compiling synstructure v0.10.2
   Compiling zeroize_derive v0.9.0 (/Users/jeff/t/t/crates/zeroize_derive)
   Compiling zeroize v0.9.2 (/Users/jeff/t/t/crates/zeroize)
error: proc-macro derive panicked
 --> zeroize/tests/zeroize_derive.rs:7:14
  |
7 |     #[derive(Zeroize)]
  |              ^^^^^^^
  |
  = help: message: unknown zeroize attribute: (drop)

error: aborting due to previous error

error: Could not compile `zeroize`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by tarcieri** [comment] 2019-07-25 14:40
The crate versions I see compiling are all the same (they should be, since Cargo.lock is checked in).

What version of Rust are you using?

**Comment by burdges** [comment] 2019-07-25 14:43
Appears the latest nightly:
```
$ rustup update
info: syncing channel updates for 'stable-x86_64-apple-darwin'
info: syncing channel updates for 'nightly-x86_64-apple-darwin'
info: checking for self-updates

   stable-x86_64-apple-darwin unchanged - rustc 1.36.0 (a53f9df32 2019-07-03)
  nightly-x86_64-apple-darwin unchanged - rustc 1.38.0-nightly (03f19f7ff 2019-07-24)
```

**Comment by tarcieri** [comment] 2019-07-25 14:44
That seems to be the main issue, then. We only test on stable.

I'll leave this open for now as I do plan on rewriting the attribute parser before the next release, which may incidentally address this.

**Comment by burdges** [comment] 2019-07-25 14:46
I see.  I suppose proc macros have some flux on nightly.

**Comment by tarcieri** [comment] 2019-07-25 22:45
This is breaking the builds for some of my docs, so I'm going to look into it ASAP.

**Comment by tarcieri** [comment] 2019-07-27 19:10
I rewrote the attribute parser in #238 and confirmed it passes on nightly.

Will release right now as v0.9.3.

**Closed** 2019-07-27 19:09 UTC
